server:
  port: 8081


spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_banking_support_transactions
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true